### ISSUE TITLE
Use XDG_CACHE_DIR instead of /tmp/ to store persistent tagging

### ISSUE THREAD

**Issue by jlargentaye** [pw4ever/awesome-wm-config#1]
You store persistent tagging information in /tmp/ (rc.lua:94). It's my understanding that the XDG_CACHE_DIR, which can be found with awful.util.getdir("cache"), is a better, more standard location for such semi-persistent information.

I was browsing around for some Zenburn Awesome theme files for 3.5 when I found your config. Awesome work!

**Comment by pw4ever** [comment]
Hi John,

I am glad you find the config useful. Could you file a pull request for your suggested patches? I think you deserve the mark on the repo for your contribution.

Just a note, besides the "rc.lua", the "README.md" may also need to be changed regarding the comment on "tmpfs" (https://github.com/pw4ever/awesome-wm-config#miscellaneous).

Thanks,
Wei.

**Comment by pw4ever** [comment]
@jlargentaye At long last, the good suggestion implemented. Thanks for the contribution.

**Comment by pw4ever** [comment]
@jlargentaye At long last, the good suggestion implemented. Thanks for the contribution.

**Comment by jlargentaye** [comment]
Great!
