### ISSUE TITLE
Stacking support?

### ISSUE THREAD

**Issue by mgabs** [pw4ever/awesome-wm-config#12]
Your readme mentions stacking support.
Is it supported in the configs?
Can you point me to where it is?

I'm currently using awesome and thinking of switching back to i3 because I miss stacking support.

**Comment by pw4ever** [comment]
Stacking/floating is enabled as the default layout, i.e., `awful.layout.suit.floating`. Alternatively, you can toggle individual client window floating state with `[modkey]+Ctrl+[space]`.

Both are mentioned in README.

You can grep for `floating` in `rc.lua` for relevant code.

**Comment by mgabs** [comment]
Thanks.
I think I mixed between stacking and tabbed.

⁣Regards,
Mohammed​

**Comment by pw4ever** [comment]
Tabbing is implemented as "tags". You can create/move/delete tags on the fly with this config.

Please search for "tag" in the README and `rc.lua` for usage.

**Comment by mgabs** [comment]
![Cheese_Sat-13Mar21_08 34](https://user-images.githubusercontent.com/66576612/111021752-51e37300-83d7-11eb-9534-331ff3e88766.png)

I was using I3 and switched to Awesome about a year ago.
I missing this functionality, grouping windows by tabs.

**Comment by pw4ever** [comment]
Hmm, maybe I did not fully understand the feature experience you are looking for here. 

But with the dynamic tagging in this config, you can create a "terminal" tag (which you can name), and put all terminals there.

If you are trying to automatically aggregate all terminals in the "term" tag, you can add a rule in `awful.rules.rules` to do that (grep for this symbol to see how this is done).

**Comment by pw4ever** [comment]
Close for now. No action required at this point.
