### ISSUE TITLE
Super-Shift-m is not working

### ISSUE THREAD

**Issue by mhdna** [pw4ever/awesome-wm-config#13]
Hello,

I've noticed that the key-binding `s-S-m` that uses the `customization.func.client_minimize()` function for minimizing a window is not working. However, when left clicking the task name in the task list, or using the drop-down menu, which uses that same function to minimize a window, it works just fine.

Thank you for this awesome Awesome config!

Edit: `s-m` for maximizing a window is not working as well :(.

**Comment by pw4ever** [comment]
Hi @mhdna,

I cannot repro this on my systems. Did you customize the config and accidentally override the key bindings?

Wei

**Comment by mhdna** [comment]
Hi again,

Thanks for your quick response.

I've actually tried them out on your original configs, and they didn't work as well. However, when I copied that same functions and keybindings to a another minimal config of mine, they did work!

Probably it has to do with the version of Awesome you're using (I'm on version 4.3), or patches you're applying to it.

**Comment by pw4ever** [comment]
I have been using this w/ vanilla `awesome` packages on Arch Linux (at home) and Debian (at work), both having awesome v4.3.

Are you sure you are on the `awesome-4.x` or `local-1pengw-4.x` branch, not the obsolete `awesome-3.x`?

**Comment by mhdna** [comment]
So you got me looking around.

I did a `checkout` to ensure that I'm on the latest `awesome-4.x` branch, and I definitely was (BTW, if I for whatever reason did use `awesome-3.x`, Awesome won't function properly).

I thought my keyboard layout setup might be the issue, and it was.
You can reproduce the issue now if you execute `setxkbmap -layout us,ara`

I haven't encountered something like this with any other window manager (this is arguably a bug in Awesome itself?).

So, I started commenting-out other keybindings in the `rc.lua` file, chunk by chunk, until I figured out that strangely enough, changing these two keybindings can fix the problem
```lua
awful.key({ modkey, }, "'", customization.func.clients_on_tag),    
---> to fix Super-m
awful.key({ modkey, "Shift" }, "'", customization.func.all_clients),    
---> to fix Super-Shift-m
```
Eventually, I remapped them to `s-\\` and `s-S-\\`, and now `s-m` and `s-S-m` are working just fine.

Thank you for your time.

**Comment by pw4ever** [comment]
Thanks for the updates!

Keyboard layout setting should be an obvious point for investigation in hindsight.  Glad you figure it out :)
