### ISSUE TITLE
Invisible tags

### ISSUE THREAD

**Issue by martindube** [pw4ever/awesome-wm-config#9]
Hi, I've been using your configuration for two years and I still love it! Great work! I recently upgraded to version version 4.0.5 and I have a different behavior. I just want to know if it is normal.

When I create an empty tag, it is not visible. For example, let's say that I have: 

tag1, tag2, tag3

tag1: 1 window
tag2: 0 window
tag3: 1 window

If my current tag is tag1, I only see tag1 and tag3. and if I hit "mod4 + n" or "mod4 + 2", I get moved to tag2. I can use it normally but it is not shown if my current tag is 1 or 3.

Personally, I find it harder to work with invisible tags so maybe it's just a bug? Or my configuration

Thanks,

**Comment by pw4ever** [comment]
Hi @martindube Thanks for trying the config and reporting the issue!

I am on 4.0.6; I am not seeing invisible empty tags.

![screenshot](https://media.giphy.com/media/l0O5Apmnc7LSs85gc/source.gif)

Could you share a screencast of the behavior on your end?

**Comment by martindube** [comment]
I moved between the tags by using "mod4 + n"

I am using Arch Linux and here are the details of my awesome version.

```
% awesome -v
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
``` 

![out2](https://cloud.githubusercontent.com/assets/4238786/23282003/69d686a0-f9ed-11e6-9459-7d51133c1c82.gif)

**Comment by pw4ever** [comment]
@martindube 
I am also on Arch Linux with identical software version.
```
$ awesome -v
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

I would look into the parameter you feed into  "awful.widget.taglist()". For example, the following is the current setting:
```lua
    customization.widgets.taglist[s] = awful.widget.taglist(s, awful.widget.taglist.filter.all, customization.widgets.taglist.buttons)
```

Did you use `awful.widget.taglist.filter.all`, or `awful.widget.taglist.filter.noempty`?

Wei.

**Comment by martindube** [comment]
I have the same line. "filter.noempty" is not used.

It is true that I modified the widgets but I have the same behavior is if I comment them. Here is what I changed: 

```
 customization.widgets.date = wibox.widget.textbox()
 vicious.register(customization.widgets.date, vicious.widgets.date, "%a %x %r %Z", 1)
@@ -1893,11 +1735,14 @@ function(s)
             layout = wibox.layout.fixed.horizontal,
             customization.widgets.keyboardlayout,
             wibox.widget.systray(),
-            customization.widgets.cpuusage,
-            customization.widgets.memusage,
-            customization.widgets.bat,
-            customization.widgets.mpdstatus,
-            customization.widgets.volume,
+            customization.widgets.mpd.icon,
+            customization.widgets.mpd.widget,
+            customization.widgets.volume.icon,
+            customization.widgets.volume.bar,
+            customization.widgets.fs.icon,
+            customization.widgets.fs.bar,
+            customization.widgets.battery.icon,
+            customization.widgets.battery.bar,
             customization.widgets.date,
             s.mylayoutbox,
         },
```

There is also the default layout that I changed.

```
 customization.default.property = {
-    layout = awful.layout.suit.floating,
+    layout = awful.layout.suit.tile,
     mwfact = 0.5,
     nmaster = 1,
     ncol = 1,
@@ -81,7 +81,7 @@ customization.default.property = {

```

That being said, could it be related to X? I use 3 screens and all of them are DISPLAY=:0 They are configured using xrandr.

**Comment by pw4ever** [comment]
@martindube Mart, I am now more certain that "noempty" is the issue here.

As shown below, with the change from "all" to "noempty", we see the "invisible empty tag" behavior.

![1](https://cloud.githubusercontent.com/assets/3914554/23284407/2213d41a-f9e0-11e6-8134-e4c5fa756ac6.gif)

One way to test whether your customization is an issue is to try the vanilla 4.0.6 config on your system. If the behavior goes away with the vanilla 4.0.6, it suggests that we need to look closer at your customization to root-cause the problem.

Wei.

**Comment by pw4ever** [comment]
@martindube 
Mart,

Have you resolved the issue on your local setup? Can we close this issue?

Wei.

**Comment by martindube** [comment]
Good morning @pw4ever,

I just made it work. You were right, it was related to the customization of my theme. For the records, I fixed the issue by commenting the `require("eminent")` line. It seems to be another implementation of dynamic tagging.

Thanks for the help and sorry for the trouble!
